### ISSUE TITLE
None of the supplied capsimg arm versions work in puae libretro on my Samsung Galaxy S7

### ISSUE THREAD

**Issue by Gagert** [rsn8887/capsimg#4]
I've got the puae libretro core up an running on my Galaxy S7 using RetroArch (the version labeled AArch64 downloaded from libretro's main page, not the ones provided in the Google Play Store).

I'm perfectly able to run both hdf- and adf files using puae just as the setup I have on my PC, but starting an ipf file on my phone just results in the Amiga Kickstart screen showing up instead of the game itself. I've downloaded the Capsimg_for_Retroarch.zip file, and have tested each of the all the capsimg.so inside the Android folder except the ones under the x86 sub-folders. Capsimg.so was copied in the Retroarch>system folder on my phone, but still I'm not able to run ipf files in puae libretro in RetroArch on my phone, with all the correct kickstart-files installed and all that.

My phone is not rooted, and viewing the System Information page in RetroArch lists the CPU Features as ASIMD and CPU Architecture as ARMv8 with CPU Cores: 8.

**Comment by Gagert** [comment]
As seen above in the "Gagert mentioned this issue" highlight, there's a logical reason regarding how Android reads external libraries that's causing this issue, that won't be auto-resolved as long as the developers behind libretro-uae can't include CAPS library in the core itself.

**Comment by rsn8887** [comment]
Thanks for the information. It makes sense to me. It is unfortunate but it seems that as it stands for now, a rooted device is needed. That's what I used in my testing years ago, a rooted Nvidia Shield Portable.
